version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ccc-creator-studio"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-a19hrpp9su1d"
s3_prefix = "ccc-creator-studio"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
